[package]
name = "tuff"
version = "0.1.0"
edition = "2021"

[lib]
name = "tuff"
path = "src/main/windows/lib.rs"

[[bin]]
name = "repl"
path = "src/main/windows/bin/repl.rs"

[[test]]
name = "integration_tests"
path = "src/test/windows/integration_tests.rs"

[[test]]
name = "test_class"
path = "src/test/windows/test_class.rs"

[[test]]
name = "test_extern"
path = "src/test/windows/test_extern.rs"

[[test]]
name = "test_interpret_all"
path = "src/test/windows/test_interpret_all.rs"

[[test]]
name = "test_method"
path = "src/test/windows/test_method.rs"

[[test]]
name = "test_struct_generics"
path = "src/test/windows/test_struct_generics.rs"

[[test]]
name = "test_use_statement"
path = "src/test/windows/test_use_statement.rs"

[[test]]
name = "test_print"
path = "src/test/windows/test_print.rs"

[[test]]
name = "test_char"
path = "src/test/windows/test_char.rs"

[dependencies]

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
too_many_arguments = "warn"