[package]
name = "tuff"
version = "0.1.0"
edition = "2021"

[lib]
name = "tuff"
path = "src/lib.rs"

[lints.clippy]
# Restrict file length
too_many_lines = "deny"

# Disallow panic-causing functions
panic = "deny"
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "warn"

# Cognitive complexity limit
cognitive_complexity = "deny"

[dependencies]
